deny-drops:
  enabled: false
  can-be-dropped:
    - stone
    - dirt
    - grass
    - 'wood:2'
death:
  enabled: true
  delete-specific-items:
    enabled: false
    items:
      - iron_helmet
      - iron_chestplate
      - iron_leggings
      - iron_boots
  delay: 5
  enabled-worlds:
    - world
    - world_nether
    - world_the_end
drop:
  enabled: true
  delay: 5
  enabled-worlds:
    - world
    - world_nether
    - world_the_end